#!/bin/bash

# Add new cron entries

  # Dump current crontab to tmp file
    crontab -l -u root > /tmp/cron.tmp

  if ! grep -q "NEMS0012" /tmp/cron.tmp; then
    if [[ ! -d /var/log/nems/nems-tools/ ]]; then
      mkdir /var/log/nems/nems-tools/
    fi
    printf "\n# nems-tools warninglight NEMS0012\n@reboot /root/nems/nems-tools/warninglight >> /var/log/nems/nems-tools/warninglight 2>&1\n" >> /tmp/cron.tmp
    cronupdate=1
    # Run it now
    /root/nems/nems-tools/warninglight >> /var/log/nems/nems-tools/warninglight 2>&1 &
  fi

  # Install piWatcher daemon, will load on boot if hat present. Otherwise, will do nothing.
  if ! grep -q "NEMS0015" /tmp/cron.tmp; then
    if (( $platform < 10 )); then
      printf "\n# piWatcher NEMS0015\n@reboot /root/nems/nems-tools/piwatcher > /dev/null 2>&1\n" >> /tmp/cron.tmp
      cronupdate=1
    fi
  fi

  # Install the NEMS Tools GPIO Extender daemon.
  if ! grep -q "NEMS0016" /tmp/cron.tmp; then
    printf "\n# NEMS Tools GPIO Extender Server NEMS0016\n@reboot /root/nems/nems-tools/gpio-extender/gpioe-server > /dev/null 2>&1\n" >> /tmp/cron.tmp
    cronupdate=1
    # Run it
    restartwarninglight=1
    /root/nems/nems-tools/gpio-extender/gpioe-server > /dev/null 2>&1 &
  fi

  # Install PiVoyager daemon, will load on boot if hat present. Otherwise, will do nothing.
  if ! grep -q "NEMS0018" /tmp/cron.tmp; then
    if (( $platform < 10 )); then
      printf "\n# PiVoyager NEMS0018\n@reboot /root/nems/nems-tools/pivoyager > /dev/null 2>&1\n" >> /tmp/cron.tmp
      cronupdate=1
    fi
  fi

  # Detect IP for NEMSeOS
  if ! grep -q "NEMS0021" /tmp/cron.tmp; then
    printf "\n# Detect NEMS Server local IP on same Subnet and set NEMS Tools config to point to it NEMS0021\n@reboot /root/nems/nems-tools/detect > /dev/null 2>&1\n" >> /tmp/cron.tmp
    cronupdate=1
  fi

  # Import revised crontab
  if [[ "$cronupdate" == "1" ]]
  then
    crontab -u root /tmp/cron.tmp
  fi

  # Remove temp file
  rm /tmp/cron.tmp

# /Add new cron entries
